name: readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: "1"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: "2"
        run: |
          cd ${GITHUB_WORKSPACE}/
          npm i
          node index.js
      - name: "3"
        run: |
          rm -rf node_modules
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README.md"
          git push --all -f https://${{ secrets.gh_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
